import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QuizProvider } from "./component/QuizProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <QuizProvider>
        <body className={`${inter.className} max-w-3xl mx-auto`}>{children}</body>
      </QuizProvider>
    </html>
  );
}
